import type { NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";

import styles from "../../styles/Home.module.css";
import ReactMarkdown from "react-markdown";

import { useRouter } from "next/router";

const About: NextPage = () => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>{router.pathname == "/favorites" ? "fav" : "index"}</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>README</main>
    </div>
  );
};

export default About;
