import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from 'react';

//Next dynamic used to disable ssr on this import
import dynamic from 'next/dynamic'
const ReactPlayer = dynamic(() => import("react-player"), { ssr: false });

import styles from '../styles/Home.module.css'


import { useQuery, gql } from '@apollo/client';


// This is a nice way to get only the data needed for the project
const GET_PLAYLIST = gql`
    query getUrl {
      playlist {
        name
        images {
          url
        }
        tracks {
          added_at
          track {
            id
            name
            preview_url
          }
        }
      }
    }
    `;



const Home: NextPage = () => {
  
  const { loading, error, data } = useQuery(GET_PLAYLIST);

  console.log(data)

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;

  return (
      <div className={styles.container}>
        <Head>
          <title>Title</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
           
          <ReactPlayer url={data.playlist.tracks[0].track.preview_url} />

        </main>

        <footer className={styles.footer}>
          Footer
        </footer>
      </div>
  )
}

export default Home
